### ISSUE TITLE
Is there a way to set arguments when running it on a file

### ISSUE THREAD

**Issue by brainopia** [Mon-Ouie/pry_debug#1]
What i mean is following, I can run `rails c` easily via ruby-debug by prepending `rdebug` in front of it.  But I can't do the same with `pry_debug`. I've tried to separate arguments with `--` still no luck.

**Comment by Mon-Ouie** [comment]
There's no really clean way, but it's still possible:

``` ruby
ARGV.replace ["c"]
```

I think parameters to the file commands and `ARGV[1..-1]` could be used for this by PryDebug directly.

**Comment by brainopia** [comment]
Thanks
