### ISSUE TITLE
Starting pry_debug from running program: doc out of date?

### ISSUE THREAD

**Issue by markjreed** [Mon-Ouie/pry_debug#2]
Starting from inside a program doesn't seem to work.  I don't have time to try to track it down right now (in the middle of the emergency that necessitated the use of a debugger in the first place), so I'm sorry this is just an issue instead of a pull request for a fix.

From the doc:

```
 require 'pry_debug'
 PryDebug.start(false) # true makes PryDebug load its own file
```

First problem - as soon as I get to the require pry_debug line, it drops into the pry(main)> prompt.
No big deal, I exit the prompt and it resumes... Then it gets to my drop-in point:

```
  PryDebug.start_pry binding
```

And there's my beautiful pry output: colorized source listing, prompt. Unfortunately, I can't do anything:

```
pry(My::Class)> n
error: debugger hasn't been started yet 
pry(My::Class)> run
NameError: uncaught throw `start_debugging!'
from /usr/lib/ruby/gems/1.8/gems/pry_debug-0.0.1/lib/pry_debug/commands.rb:74:in `throw'
```

(Unfortunately, running my program from the debugger just doesn't work - too many libraries, it takes ten minutes just to get through all the 'require's.)

**Comment by Mon-Ouie** [comment]
`PryDebug.start` is supposed to start the prompt to allow you to insert breakpoints. It is also needed to call `run` from there to make the tracer start (it's the point where the trace function is set first).

`PryDebug.start_pry` isn't really meant to be inserted at arbitrary places of the code — the point of PryDebug is to create those breakpoints at runtime, rather than inserting `binding.pry` in the code. I never thought about using it only for stepping and inserting breakpoints like that, in fact :p. I'd guess you could set `PryDebug.debugging` to true manually.

**Comment by arronmabrey** [comment]
This is exactly how I was trying to use it as well. Basically I want normal pry with the added commandes of next and step.

**Comment by jShaf** [comment]
vote +1 for pry with debugging commands so that I can start and use a program until it hits perhaps .start_pry and do stuff like next and step.

**Comment by nixme** [comment]
@markjreed, @arronmabrey, @jShaf, I've put together [pry-nav](https://github.com/nixme/pry-nav), which might be close to what you're looking for. There's no breakpoint support, but `step` and `next` are added to regular `binding.pry` and `binding.remote_pry` so you can use `binding.pry` like a breakpoint.

@Mon-Ouie, I've had to monkey-patch pry-remote a bit to get it to work, so I'll file an issue there to brainstorm better hooks?

**Comment by arronmabrey** [comment]
@nixme looks awesome that's exactly what I wanted. I will check it out on my next project. Thanks!

**Comment by Mon-Ouie** [comment]
@nixme: Feel free to do so; I've commited some changes that may solve some problems.

**Comment by nixme** [comment]
Thanks @Mon-Ouie! Looks exactly like what I needed -- will reduce my monkey patches considerably. Any chance of a new gem release?
